# Generated by Django 5.1.3 on 2024-11-12 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('screen_id', models.AutoField(primary_key=True, serialize=False)),
                ('screen_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowDetail',
            fields=[
                ('show_id', models.AutoField(primary_key=True, serialize=False)),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('theatre_id', models.AutoField(primary_key=True, serialize=False)),
                ('theatre_name', models.CharField(max_length=50)),
                ('theatre_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=50, unique=True)),
                ('movie_genre', models.CharField(max_length=30)),
                ('movie_language', models.CharField(max_length=10)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_theatre_management.screen')),
                ('showdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_theatre_management.showdetail')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_theatre_management.theatre')),
            ],
        ),
    ]
